import { dom,state,escapeHtml,formatBytes,fileRows,transport } from "./common.js";
export function setStatus(text,kind="neutral"){dom.apiStatus.textContent=text;dom.apiStatus.dataset.kind=kind}
export function emptyState(title,text){dom.results.innerHTML=`<div class="empty-state"><div class="empty-state-icon">APK</div><h3>${escapeHtml(title)}</h3><p>${escapeHtml(text)}</p></div>`}
export function loadingState(text="Ищем приложения…"){dom.results.innerHTML=`<div class="loading-state"><span class="spinner" aria-hidden="true"></span><strong>${escapeHtml(text)}</strong></div>`}
export function showError(title,message){dom.results.innerHTML=`<div class="error-state"><strong>${escapeHtml(title)}</strong><p>${escapeHtml(message)}</p><button type="button" data-action="retry-search">Повторить</button></div>`}
export function startProgress(text){state.startedAt=performance.now();dom.progressCard.hidden=false;dom.progressText.textContent=text;dom.progressTime.textContent="0 с";clearInterval(state.timer);state.timer=setInterval(()=>{dom.progressTime.textContent=`${Math.floor((performance.now()-state.startedAt)/1000)} с`},250)}
export function progress(text){dom.progressText.textContent=text} export function stopProgress(){clearInterval(state.timer);state.timer=null;dom.progressCard.hidden=true;dom.progressTime.textContent=""}
export function resultCard(app){const pkg=escapeHtml(app.package||"");return`<article class="app-card" data-package="${pkg}"><div class="app-card-head"><div class="app-icon app-icon-placeholder">GP</div><div class="app-title-wrap"><h3>${escapeHtml(app.title||app.package||"Приложение")}</h3><button class="package-copy" type="button" data-action="copy-package" title="Скопировать package name">${pkg}</button><p class="developer">${escapeHtml(app.developer||"Google Play")}</p></div></div><p class="app-description">${app.version?`Версия ${escapeHtml(app.version)}${app.versionCode?` · versionCode ${escapeHtml(app.versionCode)}`:""}`:"Выберите приложение, чтобы получить точную версию и варианты Google Play delivery."}</p><div class="app-actions"><button class="download-btn" type="button" data-action="select-app">Выбрать</button><a class="text-action" href="https://play.google.com/store/apps/details?id=${encodeURIComponent(app.package||"")}" target="_blank" rel="noopener noreferrer">Google Play ↗</a></div></article>`}
export function renderResults(apps){dom.results.innerHTML=apps.map(resultCard).join("")}
export function renderSelectedApp(app){dom.appTitle.textContent=app.title||app.package;dom.appPackage.textContent=app.package;dom.appMeta.textContent=[app.developer,app.version,app.versionCode?`versionCode ${app.versionCode}`:""].filter(Boolean).join(" · ");dom.openPlay.href=`https://play.google.com/store/apps/details?id=${encodeURIComponent(app.package)}`;dom.appCard.hidden=false}
function fileKindLabel(kind){if(kind==="BASE")return"BASE";if(kind==="SPLIT")return"SPLIT";if(kind.includes("OBB"))return"OBB";if(kind.includes("ASSET"))return"ASSET";return kind}
export function renderResolved(){if(!state.resolved.length){dom.variants.innerHTML='<div class="empty-state compact"><h3>Нет совместимых профилей</h3><p>Google Play не отдал delivery ни для одного выбранного профиля.</p></div>';return}dom.variants.innerHTML=state.resolved.map(result=>{const files=fileRows(result),apkCount=files.filter(file=>/\.apk$/i.test(file.name)).length;return`<article class="variant" data-arch="${escapeHtml(result.arch)}"><div class="variant-head"><div><div class="variant-title"><h3>${escapeHtml(result.archLabel||result.arch)}</h3><span class="pill">Google Play</span><span class="pill">vc ${escapeHtml(result.delivery.versionCode||result.app.versionCode||"—")}</span><span class="pill">${files.length} файлов</span></div><p class="variant-meta">${escapeHtml(result.app.version||"")} · base + ${result.delivery.splits.length} splits · ${result.delivery.additional.length} extras</p></div><div class="archive-actions"><button class="button primary" type="button" data-action="apks" data-arch="${escapeHtml(result.arch)}" ${apkCount?"":"disabled"}>Скачать APKS</button></div></div><div class="files">${files.map(file=>{const name=file.name||"download",href=transport.downloadUrl(file,name);return`<div class="file-row"><span class="file-kind">${escapeHtml(fileKindLabel(String(file.kind||"FILE")))}</span><span class="file-name" title="${escapeHtml(name)}">${escapeHtml(name)}</span><span class="file-size">${formatBytes(file.size)}</span><a class="button ghost small" href="${escapeHtml(href)}" rel="noopener noreferrer">Скачать</a></div>`}).join("")}</div></article>`}).join("")}