import { dom,state,escapeHtml,formatBytes,fileRows,transport } from "./common.js?v=20260902-8";
export function setStatus(text,kind="neutral"){dom.apiStatus.textContent=text;dom.apiStatus.dataset.kind=kind}
export function emptyState(title,text){dom.results.innerHTML=`<div class="empty-state"><div class="empty-state-icon">APK</div><h3>${escapeHtml(title)}</h3><p>${escapeHtml(text)}</p></div>`}
export function loadingState(text="Ищем приложения…"){dom.results.innerHTML=`<div class="loading-state"><span class="spinner" aria-hidden="true"></span><strong>${escapeHtml(text)}</strong></div>`}
export function showError(title,message){dom.results.innerHTML=`<div class="error-state"><strong>${escapeHtml(title)}</strong><p>${escapeHtml(message)}</p><button type="button" data-action="retry-search">Повторить</button></div>`}
export function startProgress(text){state.progressDepth=(state.progressDepth||0)+1;if(state.progressDepth===1){state.startedAt=performance.now();dom.progressTime.textContent="0 с";clearInterval(state.timer);state.timer=setInterval(()=>{dom.progressTime.textContent=`${Math.floor((performance.now()-state.startedAt)/1000)} с`},250)}dom.progressCard.hidden=false;dom.progressText.textContent=text}
export function progress(text){if((state.progressDepth||0)>0)dom.progressText.textContent=text}
export function stopProgress(){state.progressDepth=Math.max(0,(state.progressDepth||0)-1);if(state.progressDepth>0)return;clearInterval(state.timer);state.timer=null;dom.progressCard.hidden=true;dom.progressTime.textContent="";dom.progressText.textContent="Подготавливаю запрос."}
export function resultCard(app){const pkg=escapeHtml(app.package||"");return`<article class="app-card" data-package="${pkg}"><div class="app-card-head"><div class="app-icon app-icon-placeholder">GP</div><div class="app-title-wrap"><h3>${escapeHtml(app.title||app.package||"Приложение")}</h3><button class="package-copy" type="button" data-action="copy-package" title="Скопировать package name">${pkg}</button><p class="developer">${escapeHtml(app.developer||"Google Play")}</p></div></div><p class="app-description">${app.version?`Версия ${escapeHtml(app.version)}${app.versionCode?` · versionCode ${escapeHtml(app.versionCode)}`:""}`:"Выберите приложение, чтобы получить точную версию и варианты Google Play delivery."}</p><div class="app-actions"><button class="download-btn" type="button" data-action="select-app">Выбрать</button><a class="text-action" href="https://play.google.com/store/apps/details?id=${encodeURIComponent(app.package||"")}" target="_blank" rel="noopener noreferrer">Google Play ↗</a></div></article>`}
export function renderResults(apps){dom.results.innerHTML=apps.map(resultCard).join("")}
export function renderSelectedApp(app){dom.appTitle.textContent=app.title||app.package;dom.appPackage.textContent=app.package;dom.appMeta.textContent=[app.developer,app.version,app.versionCode?`versionCode ${app.versionCode}`:""].filter(Boolean).join(" · ");dom.openPlay.href=`https://play.google.com/store/apps/details?id=${encodeURIComponent(app.package)}`;dom.appCard.hidden=false}
function fileKindLabel(kind){if(kind==="BASE")return"BASE";if(kind==="SPLIT")return"SPLIT";if(kind.includes("OBB"))return"OBB";if(kind.includes("ASSET"))return"ASSET";return kind}
function archLabel(result){if(result.arch==="arm64")return"ARM64 · ARMv8/ARMv9";return result.archLabel||result.arch}
function deliveryInfo(result){const files=fileRows(result);const apkFiles=files.filter(file=>/\.apk$/i.test(file.name)&&file.url);const extras=files.filter(file=>!/\.apk$/i.test(file.name)&&file.url);const base=apkFiles.find(file=>String(file.kind).toUpperCase()==="BASE")||null;const monolithic=Boolean(base&&apkFiles.length===1);return{files,apkFiles,extras,base,monolithic}}
function contentsRows(files,{download=false}={}){return files.map(file=>{const name=file.name||"download";const href=download?transport.downloadUrl(file,name):"";return`<div class="file-row ${download?"extra-file-row":"composition-row"}"><span class="file-kind">${escapeHtml(fileKindLabel(String(file.kind||"FILE")))}</span><span class="file-name" title="${escapeHtml(name)}">${escapeHtml(name)}</span><span class="file-size">${formatBytes(file.size)}</span>${download?`<a class="button ghost small" href="${escapeHtml(href)}" rel="noopener noreferrer">Скачать</a>`:"<span class=\"included-mark\">в наборе</span>"}</div>`}).join("")}
export function renderResolved(){if(!state.resolved.length){dom.variants.innerHTML='<div class="empty-state compact"><h3>Нет совместимых профилей</h3><p>Google Play не отдал delivery ни для одного выбранного профиля.</p></div>';return}dom.variants.innerHTML=state.resolved.map(result=>{const info=deliveryInfo(result);const label=archLabel(result);const vc=result.delivery.versionCode||result.app.versionCode||"—";let primary;if(info.monolithic){const name=info.base.name||`${result.app.package}-${vc}-${result.arch}.apk`;const href=transport.downloadUrl(info.base,name);primary=`<a class="button primary" href="${escapeHtml(href)}" rel="noopener noreferrer">Скачать APK · ${escapeHtml(label)}</a>`}else if(info.apkFiles.length){primary=`<button class="button primary" type="button" data-action="apks" data-arch="${escapeHtml(result.arch)}">Скачать APKS · ${escapeHtml(label)}</button>`}else{primary='<button class="button primary" type="button" disabled>APK не найден</button>'}const mode=info.monolithic?"монолитный APK":`APKS · ${info.apkFiles.length} APK`;const splitCount=Math.max(0,info.apkFiles.length-(info.base?1:0));return`<article class="variant" data-arch="${escapeHtml(result.arch)}"><div class="variant-head"><div><div class="variant-title"><h3>${escapeHtml(label)}</h3><span class="pill">Google Play</span><span class="pill">vc ${escapeHtml(vc)}</span><span class="pill">${escapeHtml(mode)}</span></div><p class="variant-meta">${escapeHtml(result.app.version||"")} · ${info.monolithic?"один устанавливаемый APK":`base + ${splitCount} split/config APK`} ${info.extras.length?`· ${info.extras.length} extras`:""}</p></div><div class="archive-actions">${primary}</div></div>${info.apkFiles.length?`<details class="delivery-contents"><summary>Состав ${info.monolithic?"APK":"APKS"}: ${info.apkFiles.length} APK</summary><div class="files">${contentsRows(info.apkFiles)}</div></details>`:""}${info.extras.length?`<div class="extra-files"><div class="extra-files-title">Дополнительные файлы Google Play</div><div class="files">${contentsRows(info.extras,{download:true})}</div></div>`:""}</article>`}).join("")}
